name: "commit-and-push-protected-branch"
author: "QGX Pagamentos"
description: "Commit to protected branch"
inputs:
  name:
    description: "Git username"
    required: false
    default: "github-actions[bot]"
  email:
    description: "Git e-mail"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  message:
    description: "Git message"
    required: false
    default: "Updated by Github Actions :)"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "list"
  color: "purple"